image: node:11

stages:
  - dependencies
  - test
  - build
  - deploy

dependencies:
  stage: dependencies
  script: npm install

build:
  stage: build
  script: npm run build
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - out/**/*
  only:
    - master

test:
  stage: test
  script: echo
  allow_failure: true

deploy_RAM:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -e 'ssh -p 4040' -a ./out/ ramdeploy@snekw.com:/var/www/webgl
  only:
    - master
